#!/bin/bash
set -e -u

export VAULT_ADDR="http://${VAULT_PORT_8200_TCP_ADDR}:${VAULT_PORT_8200_TCP_PORT}"
export VAULT_TOKEN=TEST_VAULT_ROOT_TOKEN

echo "----------- SMOKE TESTS -------------"
vault status
vault token-lookup

echo "------ TEST FIXTURES ARE LOADED -------"

smokey_bear=$(vault read -field=bear secret/smokey)
if [ "$smokey_bear" != "is here" ]
then
  echo 'expected /secret/smokey to contain bear="is here"'
  exit 1
else
  echo fixtures read
fi

echo "----------- TESTS PASSED ------------"
