#!/bin/bash
set -e -u

export VAULT_ADDR="http://${VAULT_PORT_8200_TCP_ADDR}:${VAULT_PORT_8200_TCP_PORT}"
export VAULT_TOKEN=TEST_VAULT_ROOT_TOKEN

echo "----------- SMOKE TESTS -------------"
vault status
vault token-lookup

echo "------ TEST THAT FIXTURES ARE LOADED -------"

fixture_data=$(vault read -field=the_fixture secret/test_fixture)
if [ "$fixture_data" != "is loaded" ]
then
  echo 'expected /secret/test_fixture to contain ="is loaded", but got:'
  echo $fixture_data
  exit 1
else
  echo test fixture successfully read
fi

echo "----------- TESTS PASSED ------------"
